name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "27 0 * * 6"
  workflow_dispatch:
jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
